global:
  scrape_interval: 15s  # Default scrape interval
  evaluation_interval: 15s  # How frequently to evaluate rules


# Rule files to load
rule_files:
  - rules/*.yml

# Alertmanager configuration (can be expanded later)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# A scrape configuration for each service
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    scrape_interval: 5s  # More frequent scrape for API
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
