groups:
  - name: SLO_rules
    rules:
    # API Health SLO - Response time under 100ms for 95% of requests
    - record: slo:api_health:request_latency_slo_ratio
      expr: |
        sum(rate(slo_request_latency_seconds_bucket{slo="api_health", le="0.1"}[5m])) /
        sum(rate(slo_request_latency_seconds_count{slo="api_health"}[5m]))
      labels:
        slo: api_health
        window: 5m
    
    # Also compute for 1h window
    - record: slo:api_health:request_latency_slo_ratio
      expr: |
        sum(rate(slo_request_latency_seconds_bucket{slo="api_health", le="0.1"}[1h])) /
        sum(rate(slo_request_latency_seconds_count{slo="api_health"}[1h]))
      labels:
        slo: api_health
        window: 1h
        
    # Also compute for 24h window for long-term compliance
    - record: slo:api_health:request_latency_slo_ratio
      expr: |
        sum(rate(slo_request_latency_seconds_bucket{slo="api_health", le="0.1"}[24h])) /
        sum(rate(slo_request_latency_seconds_count{slo="api_health"}[24h]))
      labels:
        slo: api_health
        window: 24h
    
    # External Data SLO - Response time under 300ms for 90% of requests
    - record: slo:external_data:request_latency_slo_ratio
      expr: |
        sum(rate(slo_request_latency_seconds_bucket{slo="external_data", le="0.3"}[5m])) /
        sum(rate(slo_request_latency_seconds_count{slo="external_data"}[5m]))
      labels:
        slo: external_data
        window: 5m
    
    # Also compute for 1h window
    - record: slo:external_data:request_latency_slo_ratio
      expr: |
        sum(rate(slo_request_latency_seconds_bucket{slo="external_data", le="0.3"}[1h])) /
        sum(rate(slo_request_latency_seconds_count{slo="external_data"}[1h]))
      labels:
        slo: external_data
        window: 1h
        
    # Also compute for 24h window
    - record: slo:external_data:request_latency_slo_ratio
      expr: |
        sum(rate(slo_request_latency_seconds_bucket{slo="external_data", le="0.3"}[24h])) /
        sum(rate(slo_request_latency_seconds_count{slo="external_data"}[24h]))
      labels:
        slo: external_data
        window: 24h
    
    # Data Access SLO - Response time under 200ms for 95% of requests
    - record: slo:data_access:request_latency_slo_ratio
      expr: |
        sum(rate(slo_request_latency_seconds_bucket{slo="data_access", le="0.2"}[5m])) /
        sum(rate(slo_request_latency_seconds_count{slo="data_access"}[5m]))
      labels:
        slo: data_access
        window: 5m
        
    # Also compute for 1h window
    - record: slo:data_access:request_latency_slo_ratio
      expr: |
        sum(rate(slo_request_latency_seconds_bucket{slo="data_access", le="0.2"}[1h])) /
        sum(rate(slo_request_latency_seconds_count{slo="data_access"}[1h]))
      labels:
        slo: data_access
        window: 1h
        
    # Also compute for 24h window
    - record: slo:data_access:request_latency_slo_ratio
      expr: |
        sum(rate(slo_request_latency_seconds_bucket{slo="data_access", le="0.2"}[24h])) /
        sum(rate(slo_request_latency_seconds_count{slo="data_access"}[24h]))
      labels:
        slo: data_access
        window: 24h

    # Error Budget SLO - Less than a 1% error rate for all endpoints
    - record: slo:api:error_ratio
      expr: |
        sum(rate(slo_errors_total[5m])) / 
        sum(rate(request_duration_seconds_count[5m]))
      labels:
        slo: error_budget
        window: 5m
        
    # Also compute for 1h window
    - record: slo:api:error_ratio
      expr: |
        sum(rate(slo_errors_total[1h])) / 
        sum(rate(request_duration_seconds_count[1h]))
      labels:
        slo: error_budget
        window: 1h
        
    # Also compute for 24h window
    - record: slo:api:error_ratio
      expr: |
        sum(rate(slo_errors_total[24h])) / 
        sum(rate(request_duration_seconds_count[24h]))
      labels:
        slo: error_budget
        window: 24h
    
    # Calculate error budget consumption rate
    - record: slo:api_health:error_budget_burn_rate
      expr: |
        (0.95 - slo:api_health:request_latency_slo_ratio{window="5m"}) / 0.05
      labels:
        slo: api_health
        window: 5m
        
    - record: slo:external_data:error_budget_burn_rate
      expr: |
        (0.90 - slo:external_data:request_latency_slo_ratio{window="5m"}) / 0.10
      labels:
        slo: external_data
        window: 5m
        
    - record: slo:data_access:error_budget_burn_rate
      expr: |
        (0.95 - slo:data_access:request_latency_slo_ratio{window="5m"}) / 0.05
      labels:
        slo: data_access
        window: 5m
        
    # Update the compliance gauge metrics for use in dashboards
    - record: slo_compliance_ratio
      expr: slo:api_health:request_latency_slo_ratio{window="5m"}
      labels:
        endpoint: health_check
        slo: api_health
        window: 5m
        
    - record: slo_compliance_ratio
      expr: slo:api_health:request_latency_slo_ratio{window="1h"}
      labels:
        endpoint: health_check
        slo: api_health
        window: 1h
        
    - record: slo_compliance_ratio
      expr: slo:api_health:request_latency_slo_ratio{window="24h"}
      labels:
        endpoint: health_check
        slo: api_health
        window: 24h
        
    - record: slo_compliance_ratio
      expr: slo:external_data:request_latency_slo_ratio{window="5m"}
      labels:
        endpoint: get_external_data
        slo: external_data
        window: 5m
        
    - record: slo_compliance_ratio
      expr: slo:external_data:request_latency_slo_ratio{window="1h"}
      labels:
        endpoint: get_external_data
        slo: external_data
        window: 1h
        
    - record: slo_compliance_ratio
      expr: slo:external_data:request_latency_slo_ratio{window="24h"}
      labels:
        endpoint: get_external_data
        slo: external_data
        window: 24h
        
    - record: slo_compliance_ratio
      expr: slo:data_access:request_latency_slo_ratio{window="5m"}
      labels:
        endpoint: data_access
        slo: data_access
        window: 5m
        
    - record: slo_compliance_ratio
      expr: slo:data_access:request_latency_slo_ratio{window="1h"}
      labels:
        endpoint: data_access
        slo: data_access
        window: 1h
        
    - record: slo_compliance_ratio
      expr: slo:data_access:request_latency_slo_ratio{window="24h"}
      labels:
        endpoint: data_access
        slo: data_access
        window: 24h
        
    # Error budget remaining calculations
    - record: slo_error_budget_remaining
      expr: |
        1 - (0.95 - slo:api_health:request_latency_slo_ratio{window="5m"}) / 0.05
      labels:
        slo: api_health
        window: 5m
        
    - record: slo_error_budget_remaining
      expr: |
        1 - (0.95 - slo:api_health:request_latency_slo_ratio{window="1h"}) / 0.05
      labels:
        slo: api_health
        window: 1h
        
    - record: slo_error_budget_remaining
      expr: |
        1 - (0.95 - slo:api_health:request_latency_slo_ratio{window="24h"}) / 0.05
      labels:
        slo: api_health
        window: 24h
        
    - record: slo_error_budget_remaining
      expr: |
        1 - (0.90 - slo:external_data:request_latency_slo_ratio{window="5m"}) / 0.10
      labels:
        slo: external_data
        window: 5m
        
    - record: slo_error_budget_remaining
      expr: |
        1 - (0.90 - slo:external_data:request_latency_slo_ratio{window="1h"}) / 0.10
      labels:
        slo: external_data
        window: 1h
        
    - record: slo_error_budget_remaining
      expr: |
        1 - (0.90 - slo:external_data:request_latency_slo_ratio{window="24h"}) / 0.10
      labels:
        slo: external_data
        window: 24h
        
    - record: slo_error_budget_remaining
      expr: |
        1 - (0.95 - slo:data_access:request_latency_slo_ratio{window="5m"}) / 0.05
      labels:
        slo: data_access
        window: 5m
        
    - record: slo_error_budget_remaining
      expr: |
        1 - (0.95 - slo:data_access:request_latency_slo_ratio{window="1h"}) / 0.05
      labels:
        slo: data_access
        window: 1h
        
    - record: slo_error_budget_remaining
      expr: |
        1 - (0.95 - slo:data_access:request_latency_slo_ratio{window="24h"}) / 0.05
      labels:
        slo: data_access
        window: 24h
        
    # Alerting rules
    - alert: ApiHealthSloBreached
      expr: slo:api_health:request_latency_slo_ratio{window="5m"} < 0.95
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "API Health SLO Breach"
        description: "API Health endpoint is not meeting its SLO of 95% of requests under 100ms. Current value: {{ $value }}"
        dashboard_url: "http://localhost:3001/d/trace-overview/trace-overview"
        
    # Alert when burning through error budget too quickly
    - alert: ApiHealthErrorBudgetBurningFast
      expr: slo_error_budget_remaining{slo="api_health", window="1h"} < 0.5
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "API Health Error Budget Burning Fast"
        description: "API Health SLO error budget is being consumed too quickly. Only {{ $value | humanizePercentage }} remaining for the 1h window."
        dashboard_url: "http://localhost:3001/d/trace-overview/trace-overview"
        
    - alert: ExternalDataSloBreached
      expr: slo:external_data:request_latency_slo_ratio{window="5m"} < 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "External Data SLO Breach"
        description: "External Data endpoint is not meeting its SLO of 90% of requests under 300ms. Current value: {{ $value }}"
        dashboard_url: "http://localhost:3001/d/trace-overview/trace-overview"
        
    - alert: ExternalDataErrorBudgetBurningFast
      expr: slo_error_budget_remaining{slo="external_data", window="1h"} < 0.5
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "External Data Error Budget Burning Fast"
        description: "External Data SLO error budget is being consumed too quickly. Only {{ $value | humanizePercentage }} remaining for the 1h window."
        dashboard_url: "http://localhost:3001/d/trace-overview/trace-overview"
        
    - alert: DataAccessSloBreached
      expr: slo:data_access:request_latency_slo_ratio{window="5m"} < 0.95
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Data Access SLO Breach"
        description: "Data Access endpoints are not meeting their SLO of 95% of requests under 200ms. Current value: {{ $value }}"
        dashboard_url: "http://localhost:3001/d/trace-overview/trace-overview"
        
    - alert: DataAccessErrorBudgetBurningFast
      expr: slo_error_budget_remaining{slo="data_access", window="1h"} < 0.5
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Data Access Error Budget Burning Fast"
        description: "Data Access SLO error budget is being consumed too quickly. Only {{ $value | humanizePercentage }} remaining for the 1h window."
        dashboard_url: "http://localhost:3001/d/trace-overview/trace-overview"
        
    - alert: ErrorBudgetBreach
      expr: slo:api:error_ratio{window="5m"} > 0.01
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Error Budget Breach"
        description: "Error rate is exceeding the 1% threshold. Current error rate: {{ $value | humanizePercentage }}"
        dashboard_url: "http://localhost:3001/d/trace-overview/trace-overview"
        
    # Critical alert for near-depleted error budget
    - alert: ErrorBudgetCritical
      expr: slo_error_budget_remaining{window="24h"} < 0.2
      for: 30m
      labels:
        severity: critical
      annotations:
        summary: "Error Budget Critically Low"
        description: "SLO error budget for {{ $labels.slo }} is critically low with only {{ $value | humanizePercentage }} remaining for the 24h window."
        dashboard_url: "http://localhost:3001/d/trace-overview/trace-overview"
